# Generated by Django 4.0.1 on 2022-02-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='pic',
            field=models.ImageField(default='no_ingredients.jpeg', upload_to='ingredients'),
        ),
    ]
